services:
  - type: web
    name: smartscribe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python interface.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
